# Generated by Django 3.2.1 on 2021-05-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('date', models.CharField(max_length=10)),
                ('reason', models.CharField(max_length=125)),
            ],
        ),
    ]
